### PR TITLE
Django Tutorial Part 11: Deploying Django to production

### PR DESCRIPTION
**Pull request by Atanna128**

### CODE REVIEW

**Comment by Atanna128** [comment]
ready

**Comment by thaodtd-0665** [comment]
pull này conflict code rồi em

**Comment by thaodtd-0665** [comment]
pull này conflict code nhé

**Comment by thaodtd-0665** [comment]
commented

**Comment by Atanna128** [comment]
ready

**Review by thaodtd-0665 — APPROVED** [review]

**Comment by thaodtd-0665** [comment]
merged

**Pull request merged**
